/**
 * This class is generated by jOOQ
 */
package persistencia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asientodetalle extends org.jooq.impl.TableImpl<persistencia.tables.records.AsientodetalleRecord> {

	private static final long serialVersionUID = 419768410;

	/**
	 * The singleton instance of <code>modulo_contable_smartwork.asientodetalle</code>
	 */
	public static final persistencia.tables.Asientodetalle ASIENTODETALLE = new persistencia.tables.Asientodetalle();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<persistencia.tables.records.AsientodetalleRecord> getRecordType() {
		return persistencia.tables.records.AsientodetalleRecord.class;
	}

	/**
	 * The column <code>modulo_contable_smartwork.asientodetalle.ASIENTODETALLEID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientodetalleRecord, java.lang.Integer> ASIENTODETALLEID = createField("ASIENTODETALLEID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asientodetalle.ID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientodetalleRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asientodetalle.ASIENTOID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientodetalleRecord, java.lang.Integer> ASIENTOID = createField("ASIENTOID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asientodetalle.DESCRIPCION</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientodetalleRecord, java.lang.String> DESCRIPCION = createField("DESCRIPCION", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asientodetalle.DEBE</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientodetalleRecord, java.lang.Double> DEBE = createField("DEBE", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asientodetalle.HABER</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientodetalleRecord, java.lang.Double> HABER = createField("HABER", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * Create a <code>modulo_contable_smartwork.asientodetalle</code> table reference
	 */
	public Asientodetalle() {
		this("asientodetalle", null);
	}

	/**
	 * Create an aliased <code>modulo_contable_smartwork.asientodetalle</code> table reference
	 */
	public Asientodetalle(java.lang.String alias) {
		this(alias, persistencia.tables.Asientodetalle.ASIENTODETALLE);
	}

	private Asientodetalle(java.lang.String alias, org.jooq.Table<persistencia.tables.records.AsientodetalleRecord> aliased) {
		this(alias, aliased, null);
	}

	private Asientodetalle(java.lang.String alias, org.jooq.Table<persistencia.tables.records.AsientodetalleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, persistencia.ModuloContableSmartwork.MODULO_CONTABLE_SMARTWORK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<persistencia.tables.records.AsientodetalleRecord> getPrimaryKey() {
		return persistencia.Keys.KEY_ASIENTODETALLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<persistencia.tables.records.AsientodetalleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<persistencia.tables.records.AsientodetalleRecord>>asList(persistencia.Keys.KEY_ASIENTODETALLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<persistencia.tables.records.AsientodetalleRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<persistencia.tables.records.AsientodetalleRecord, ?>>asList(persistencia.Keys.FK_RELATIONSHIP_3, persistencia.Keys.FK_RELATIONSHIP_4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public persistencia.tables.Asientodetalle as(java.lang.String alias) {
		return new persistencia.tables.Asientodetalle(alias, this);
	}

	/**
	 * Rename this table
	 */
	public persistencia.tables.Asientodetalle rename(java.lang.String name) {
		return new persistencia.tables.Asientodetalle(name, null);
	}
}
