/**
 * This class is generated by jOOQ
 */
package persistencia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asiento extends org.jooq.impl.TableImpl<persistencia.tables.records.AsientoRecord> {

	private static final long serialVersionUID = 1462025583;

	/**
	 * The singleton instance of <code>modulo_contable_smartwork.asiento</code>
	 */
	public static final persistencia.tables.Asiento ASIENTO = new persistencia.tables.Asiento();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<persistencia.tables.records.AsientoRecord> getRecordType() {
		return persistencia.tables.records.AsientoRecord.class;
	}

	/**
	 * The column <code>modulo_contable_smartwork.asiento.ASIENTOID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientoRecord, java.lang.Integer> ASIENTOID = createField("ASIENTOID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asiento.PERIODOCONTABLEID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientoRecord, java.lang.Integer> PERIODOCONTABLEID = createField("PERIODOCONTABLEID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asiento.TIPOMOVIMIENTOID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientoRecord, java.lang.Integer> TIPOMOVIMIENTOID = createField("TIPOMOVIMIENTOID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asiento.FECHACREACION</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientoRecord, java.sql.Timestamp> FECHACREACION = createField("FECHACREACION", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asiento.CONCEPTO</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientoRecord, java.lang.String> CONCEPTO = createField("CONCEPTO", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.asiento.ESTADO</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.AsientoRecord, java.lang.Integer> ESTADO = createField("ESTADO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>modulo_contable_smartwork.asiento</code> table reference
	 */
	public Asiento() {
		this("asiento", null);
	}

	/**
	 * Create an aliased <code>modulo_contable_smartwork.asiento</code> table reference
	 */
	public Asiento(java.lang.String alias) {
		this(alias, persistencia.tables.Asiento.ASIENTO);
	}

	private Asiento(java.lang.String alias, org.jooq.Table<persistencia.tables.records.AsientoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Asiento(java.lang.String alias, org.jooq.Table<persistencia.tables.records.AsientoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, persistencia.ModuloContableSmartwork.MODULO_CONTABLE_SMARTWORK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<persistencia.tables.records.AsientoRecord> getPrimaryKey() {
		return persistencia.Keys.KEY_ASIENTO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<persistencia.tables.records.AsientoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<persistencia.tables.records.AsientoRecord>>asList(persistencia.Keys.KEY_ASIENTO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<persistencia.tables.records.AsientoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<persistencia.tables.records.AsientoRecord, ?>>asList(persistencia.Keys.FK_RELATIONSHIP_2, persistencia.Keys.FK_RELATIONSHIP_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public persistencia.tables.Asiento as(java.lang.String alias) {
		return new persistencia.tables.Asiento(alias, this);
	}

	/**
	 * Rename this table
	 */
	public persistencia.tables.Asiento rename(java.lang.String name) {
		return new persistencia.tables.Asiento(name, null);
	}
}
