/**
 * This class is generated by jOOQ
 */
package persistencia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Periodocontable extends org.jooq.impl.TableImpl<persistencia.tables.records.PeriodocontableRecord> {

	private static final long serialVersionUID = -242034731;

	/**
	 * The singleton instance of <code>modulo_contable_smartwork.periodocontable</code>
	 */
	public static final persistencia.tables.Periodocontable PERIODOCONTABLE = new persistencia.tables.Periodocontable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<persistencia.tables.records.PeriodocontableRecord> getRecordType() {
		return persistencia.tables.records.PeriodocontableRecord.class;
	}

	/**
	 * The column <code>modulo_contable_smartwork.periodocontable.PERIODOCONTABLEID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PeriodocontableRecord, java.lang.Integer> PERIODOCONTABLEID = createField("PERIODOCONTABLEID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.periodocontable.FECHAINICIO</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PeriodocontableRecord, java.sql.Timestamp> FECHAINICIO = createField("FECHAINICIO", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.periodocontable.FECHAFINAL</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PeriodocontableRecord, java.sql.Timestamp> FECHAFINAL = createField("FECHAFINAL", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.periodocontable.NOMBREPERIODO</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PeriodocontableRecord, java.lang.String> NOMBREPERIODO = createField("NOMBREPERIODO", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.periodocontable.ESTADO</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PeriodocontableRecord, java.lang.Integer> ESTADO = createField("ESTADO", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>modulo_contable_smartwork.periodocontable</code> table reference
	 */
	public Periodocontable() {
		this("periodocontable", null);
	}

	/**
	 * Create an aliased <code>modulo_contable_smartwork.periodocontable</code> table reference
	 */
	public Periodocontable(java.lang.String alias) {
		this(alias, persistencia.tables.Periodocontable.PERIODOCONTABLE);
	}

	private Periodocontable(java.lang.String alias, org.jooq.Table<persistencia.tables.records.PeriodocontableRecord> aliased) {
		this(alias, aliased, null);
	}

	private Periodocontable(java.lang.String alias, org.jooq.Table<persistencia.tables.records.PeriodocontableRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, persistencia.ModuloContableSmartwork.MODULO_CONTABLE_SMARTWORK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<persistencia.tables.records.PeriodocontableRecord> getPrimaryKey() {
		return persistencia.Keys.KEY_PERIODOCONTABLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<persistencia.tables.records.PeriodocontableRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<persistencia.tables.records.PeriodocontableRecord>>asList(persistencia.Keys.KEY_PERIODOCONTABLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public persistencia.tables.Periodocontable as(java.lang.String alias) {
		return new persistencia.tables.Periodocontable(alias, this);
	}

	/**
	 * Rename this table
	 */
	public persistencia.tables.Periodocontable rename(java.lang.String name) {
		return new persistencia.tables.Periodocontable(name, null);
	}
}
