/**
 * This class is generated by jOOQ
 */
package persistencia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plandecuenta extends org.jooq.impl.TableImpl<persistencia.tables.records.PlandecuentaRecord> {

	private static final long serialVersionUID = 1323748154;

	/**
	 * The singleton instance of <code>modulo_contable_smartwork.plandecuenta</code>
	 */
	public static final persistencia.tables.Plandecuenta PLANDECUENTA = new persistencia.tables.Plandecuenta();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<persistencia.tables.records.PlandecuentaRecord> getRecordType() {
		return persistencia.tables.records.PlandecuentaRecord.class;
	}

	/**
	 * The column <code>modulo_contable_smartwork.plandecuenta.ID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PlandecuentaRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.plandecuenta.PLA_ID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PlandecuentaRecord, java.lang.Integer> PLA_ID = createField("PLA_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.plandecuenta.CODIGOCONTABLE</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PlandecuentaRecord, java.lang.String> CODIGOCONTABLE = createField("CODIGOCONTABLE", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.plandecuenta.NOMBRECUENTA</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PlandecuentaRecord, java.lang.String> NOMBRECUENTA = createField("NOMBRECUENTA", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.plandecuenta.TIPOCUENTA</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PlandecuentaRecord, java.lang.Integer> TIPOCUENTA = createField("TIPOCUENTA", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.plandecuenta.ESTADO</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.PlandecuentaRecord, java.lang.Integer> ESTADO = createField("ESTADO", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>modulo_contable_smartwork.plandecuenta</code> table reference
	 */
	public Plandecuenta() {
		this("plandecuenta", null);
	}

	/**
	 * Create an aliased <code>modulo_contable_smartwork.plandecuenta</code> table reference
	 */
	public Plandecuenta(java.lang.String alias) {
		this(alias, persistencia.tables.Plandecuenta.PLANDECUENTA);
	}

	private Plandecuenta(java.lang.String alias, org.jooq.Table<persistencia.tables.records.PlandecuentaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Plandecuenta(java.lang.String alias, org.jooq.Table<persistencia.tables.records.PlandecuentaRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, persistencia.ModuloContableSmartwork.MODULO_CONTABLE_SMARTWORK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<persistencia.tables.records.PlandecuentaRecord> getPrimaryKey() {
		return persistencia.Keys.KEY_PLANDECUENTA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<persistencia.tables.records.PlandecuentaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<persistencia.tables.records.PlandecuentaRecord>>asList(persistencia.Keys.KEY_PLANDECUENTA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<persistencia.tables.records.PlandecuentaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<persistencia.tables.records.PlandecuentaRecord, ?>>asList(persistencia.Keys.FK_RELATIONSHIP_7);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public persistencia.tables.Plandecuenta as(java.lang.String alias) {
		return new persistencia.tables.Plandecuenta(alias, this);
	}

	/**
	 * Rename this table
	 */
	public persistencia.tables.Plandecuenta rename(java.lang.String name) {
		return new persistencia.tables.Plandecuenta(name, null);
	}
}
