/**
 * This class is generated by jOOQ
 */
package persistencia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Saldoperiodo extends org.jooq.impl.TableImpl<persistencia.tables.records.SaldoperiodoRecord> {

	private static final long serialVersionUID = -1487545123;

	/**
	 * The singleton instance of <code>modulo_contable_smartwork.saldoperiodo</code>
	 */
	public static final persistencia.tables.Saldoperiodo SALDOPERIODO = new persistencia.tables.Saldoperiodo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<persistencia.tables.records.SaldoperiodoRecord> getRecordType() {
		return persistencia.tables.records.SaldoperiodoRecord.class;
	}

	/**
	 * The column <code>modulo_contable_smartwork.saldoperiodo.SALDOPERIODOID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.SaldoperiodoRecord, java.lang.Integer> SALDOPERIODOID = createField("SALDOPERIODOID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.saldoperiodo.ID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.SaldoperiodoRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.saldoperiodo.PERIODOCONTABLEID</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.SaldoperiodoRecord, java.lang.Integer> PERIODOCONTABLEID = createField("PERIODOCONTABLEID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>modulo_contable_smartwork.saldoperiodo.SALDODEBE</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.SaldoperiodoRecord, java.lang.Double> SALDODEBE = createField("SALDODEBE", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.saldoperiodo.SALDOHABER</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.SaldoperiodoRecord, java.lang.Double> SALDOHABER = createField("SALDOHABER", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * The column <code>modulo_contable_smartwork.saldoperiodo.SALDOFINAL</code>.
	 */
	public final org.jooq.TableField<persistencia.tables.records.SaldoperiodoRecord, java.lang.Double> SALDOFINAL = createField("SALDOFINAL", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * Create a <code>modulo_contable_smartwork.saldoperiodo</code> table reference
	 */
	public Saldoperiodo() {
		this("saldoperiodo", null);
	}

	/**
	 * Create an aliased <code>modulo_contable_smartwork.saldoperiodo</code> table reference
	 */
	public Saldoperiodo(java.lang.String alias) {
		this(alias, persistencia.tables.Saldoperiodo.SALDOPERIODO);
	}

	private Saldoperiodo(java.lang.String alias, org.jooq.Table<persistencia.tables.records.SaldoperiodoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Saldoperiodo(java.lang.String alias, org.jooq.Table<persistencia.tables.records.SaldoperiodoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, persistencia.ModuloContableSmartwork.MODULO_CONTABLE_SMARTWORK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<persistencia.tables.records.SaldoperiodoRecord> getPrimaryKey() {
		return persistencia.Keys.KEY_SALDOPERIODO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<persistencia.tables.records.SaldoperiodoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<persistencia.tables.records.SaldoperiodoRecord>>asList(persistencia.Keys.KEY_SALDOPERIODO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<persistencia.tables.records.SaldoperiodoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<persistencia.tables.records.SaldoperiodoRecord, ?>>asList(persistencia.Keys.FK_RELATIONSHIP_6, persistencia.Keys.FK_RELATIONSHIP_5);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public persistencia.tables.Saldoperiodo as(java.lang.String alias) {
		return new persistencia.tables.Saldoperiodo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public persistencia.tables.Saldoperiodo rename(java.lang.String name) {
		return new persistencia.tables.Saldoperiodo(name, null);
	}
}
