/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsientoRecord extends org.jooq.impl.UpdatableRecordImpl<persistencia.tables.records.AsientoRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1598151666;

	/**
	 * Setter for <code>modulo_contable_smartwork.asiento.ASIENTOID</code>.
	 */
	public void setAsientoid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asiento.ASIENTOID</code>.
	 */
	public java.lang.Integer getAsientoid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asiento.PERIODOCONTABLEID</code>.
	 */
	public void setPeriodocontableid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asiento.PERIODOCONTABLEID</code>.
	 */
	public java.lang.Integer getPeriodocontableid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asiento.TIPOMOVIMIENTOID</code>.
	 */
	public void setTipomovimientoid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asiento.TIPOMOVIMIENTOID</code>.
	 */
	public java.lang.Integer getTipomovimientoid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asiento.FECHACREACION</code>.
	 */
	public void setFechacreacion(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asiento.FECHACREACION</code>.
	 */
	public java.sql.Timestamp getFechacreacion() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asiento.CONCEPTO</code>.
	 */
	public void setConcepto(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asiento.CONCEPTO</code>.
	 */
	public java.lang.String getConcepto() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asiento.ESTADO</code>.
	 */
	public void setEstado(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asiento.ESTADO</code>.
	 */
	public java.lang.Integer getEstado() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return persistencia.tables.Asiento.ASIENTO.ASIENTOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return persistencia.tables.Asiento.ASIENTO.PERIODOCONTABLEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return persistencia.tables.Asiento.ASIENTO.TIPOMOVIMIENTOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return persistencia.tables.Asiento.ASIENTO.FECHACREACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return persistencia.tables.Asiento.ASIENTO.CONCEPTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return persistencia.tables.Asiento.ASIENTO.ESTADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAsientoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getPeriodocontableid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getTipomovimientoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getFechacreacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getConcepto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getEstado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientoRecord value1(java.lang.Integer value) {
		setAsientoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientoRecord value2(java.lang.Integer value) {
		setPeriodocontableid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientoRecord value3(java.lang.Integer value) {
		setTipomovimientoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientoRecord value4(java.sql.Timestamp value) {
		setFechacreacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientoRecord value5(java.lang.String value) {
		setConcepto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientoRecord value6(java.lang.Integer value) {
		setEstado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientoRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.sql.Timestamp value4, java.lang.String value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AsientoRecord
	 */
	public AsientoRecord() {
		super(persistencia.tables.Asiento.ASIENTO);
	}

	/**
	 * Create a detached, initialised AsientoRecord
	 */
	public AsientoRecord(java.lang.Integer asientoid, java.lang.Integer periodocontableid, java.lang.Integer tipomovimientoid, java.sql.Timestamp fechacreacion, java.lang.String concepto, java.lang.Integer estado) {
		super(persistencia.tables.Asiento.ASIENTO);

		setValue(0, asientoid);
		setValue(1, periodocontableid);
		setValue(2, tipomovimientoid);
		setValue(3, fechacreacion);
		setValue(4, concepto);
		setValue(5, estado);
	}
}
