/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsientodetalleRecord extends org.jooq.impl.UpdatableRecordImpl<persistencia.tables.records.AsientodetalleRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double> {

	private static final long serialVersionUID = 2035671941;

	/**
	 * Setter for <code>modulo_contable_smartwork.asientodetalle.ASIENTODETALLEID</code>.
	 */
	public void setAsientodetalleid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asientodetalle.ASIENTODETALLEID</code>.
	 */
	public java.lang.Integer getAsientodetalleid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asientodetalle.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asientodetalle.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asientodetalle.ASIENTOID</code>.
	 */
	public void setAsientoid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asientodetalle.ASIENTOID</code>.
	 */
	public java.lang.Integer getAsientoid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asientodetalle.DESCRIPCION</code>.
	 */
	public void setDescripcion(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asientodetalle.DESCRIPCION</code>.
	 */
	public java.lang.String getDescripcion() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asientodetalle.DEBE</code>.
	 */
	public void setDebe(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asientodetalle.DEBE</code>.
	 */
	public java.lang.Double getDebe() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.asientodetalle.HABER</code>.
	 */
	public void setHaber(java.lang.Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.asientodetalle.HABER</code>.
	 */
	public java.lang.Double getHaber() {
		return (java.lang.Double) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return persistencia.tables.Asientodetalle.ASIENTODETALLE.ASIENTODETALLEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return persistencia.tables.Asientodetalle.ASIENTODETALLE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return persistencia.tables.Asientodetalle.ASIENTODETALLE.ASIENTOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return persistencia.tables.Asientodetalle.ASIENTODETALLE.DESCRIPCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return persistencia.tables.Asientodetalle.ASIENTODETALLE.DEBE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field6() {
		return persistencia.tables.Asientodetalle.ASIENTODETALLE.HABER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAsientodetalleid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getAsientoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDescripcion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getDebe();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value6() {
		return getHaber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientodetalleRecord value1(java.lang.Integer value) {
		setAsientodetalleid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientodetalleRecord value2(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientodetalleRecord value3(java.lang.Integer value) {
		setAsientoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientodetalleRecord value4(java.lang.String value) {
		setDescripcion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientodetalleRecord value5(java.lang.Double value) {
		setDebe(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientodetalleRecord value6(java.lang.Double value) {
		setHaber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsientodetalleRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4, java.lang.Double value5, java.lang.Double value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AsientodetalleRecord
	 */
	public AsientodetalleRecord() {
		super(persistencia.tables.Asientodetalle.ASIENTODETALLE);
	}

	/**
	 * Create a detached, initialised AsientodetalleRecord
	 */
	public AsientodetalleRecord(java.lang.Integer asientodetalleid, java.lang.Integer id, java.lang.Integer asientoid, java.lang.String descripcion, java.lang.Double debe, java.lang.Double haber) {
		super(persistencia.tables.Asientodetalle.ASIENTODETALLE);

		setValue(0, asientodetalleid);
		setValue(1, id);
		setValue(2, asientoid);
		setValue(3, descripcion);
		setValue(4, debe);
		setValue(5, haber);
	}
}
