/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlandecuentaRecord extends org.jooq.impl.UpdatableRecordImpl<persistencia.tables.records.PlandecuentaRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1863639861;

	/**
	 * Setter for <code>modulo_contable_smartwork.plandecuenta.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.plandecuenta.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.plandecuenta.PLA_ID</code>.
	 */
	public void setPlaId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.plandecuenta.PLA_ID</code>.
	 */
	public java.lang.Integer getPlaId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.plandecuenta.CODIGOCONTABLE</code>.
	 */
	public void setCodigocontable(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.plandecuenta.CODIGOCONTABLE</code>.
	 */
	public java.lang.String getCodigocontable() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.plandecuenta.NOMBRECUENTA</code>.
	 */
	public void setNombrecuenta(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.plandecuenta.NOMBRECUENTA</code>.
	 */
	public java.lang.String getNombrecuenta() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.plandecuenta.TIPOCUENTA</code>.
	 */
	public void setTipocuenta(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.plandecuenta.TIPOCUENTA</code>.
	 */
	public java.lang.Integer getTipocuenta() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.plandecuenta.ESTADO</code>.
	 */
	public void setEstado(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.plandecuenta.ESTADO</code>.
	 */
	public java.lang.Integer getEstado() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return persistencia.tables.Plandecuenta.PLANDECUENTA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return persistencia.tables.Plandecuenta.PLANDECUENTA.PLA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return persistencia.tables.Plandecuenta.PLANDECUENTA.CODIGOCONTABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return persistencia.tables.Plandecuenta.PLANDECUENTA.NOMBRECUENTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return persistencia.tables.Plandecuenta.PLANDECUENTA.TIPOCUENTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return persistencia.tables.Plandecuenta.PLANDECUENTA.ESTADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getPlaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCodigocontable();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getNombrecuenta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getTipocuenta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getEstado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlandecuentaRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlandecuentaRecord value2(java.lang.Integer value) {
		setPlaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlandecuentaRecord value3(java.lang.String value) {
		setCodigocontable(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlandecuentaRecord value4(java.lang.String value) {
		setNombrecuenta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlandecuentaRecord value5(java.lang.Integer value) {
		setTipocuenta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlandecuentaRecord value6(java.lang.Integer value) {
		setEstado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlandecuentaRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlandecuentaRecord
	 */
	public PlandecuentaRecord() {
		super(persistencia.tables.Plandecuenta.PLANDECUENTA);
	}

	/**
	 * Create a detached, initialised PlandecuentaRecord
	 */
	public PlandecuentaRecord(java.lang.Integer id, java.lang.Integer plaId, java.lang.String codigocontable, java.lang.String nombrecuenta, java.lang.Integer tipocuenta, java.lang.Integer estado) {
		super(persistencia.tables.Plandecuenta.PLANDECUENTA);

		setValue(0, id);
		setValue(1, plaId);
		setValue(2, codigocontable);
		setValue(3, nombrecuenta);
		setValue(4, tipocuenta);
		setValue(5, estado);
	}
}
