/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SaldoperiodoRecord extends org.jooq.impl.UpdatableRecordImpl<persistencia.tables.records.SaldoperiodoRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double> {

	private static final long serialVersionUID = 403704542;

	/**
	 * Setter for <code>modulo_contable_smartwork.saldoperiodo.SALDOPERIODOID</code>.
	 */
	public void setSaldoperiodoid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.saldoperiodo.SALDOPERIODOID</code>.
	 */
	public java.lang.Integer getSaldoperiodoid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.saldoperiodo.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.saldoperiodo.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.saldoperiodo.PERIODOCONTABLEID</code>.
	 */
	public void setPeriodocontableid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.saldoperiodo.PERIODOCONTABLEID</code>.
	 */
	public java.lang.Integer getPeriodocontableid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.saldoperiodo.SALDODEBE</code>.
	 */
	public void setSaldodebe(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.saldoperiodo.SALDODEBE</code>.
	 */
	public java.lang.Double getSaldodebe() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.saldoperiodo.SALDOHABER</code>.
	 */
	public void setSaldohaber(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.saldoperiodo.SALDOHABER</code>.
	 */
	public java.lang.Double getSaldohaber() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.saldoperiodo.SALDOFINAL</code>.
	 */
	public void setSaldofinal(java.lang.Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.saldoperiodo.SALDOFINAL</code>.
	 */
	public java.lang.Double getSaldofinal() {
		return (java.lang.Double) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return persistencia.tables.Saldoperiodo.SALDOPERIODO.SALDOPERIODOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return persistencia.tables.Saldoperiodo.SALDOPERIODO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return persistencia.tables.Saldoperiodo.SALDOPERIODO.PERIODOCONTABLEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return persistencia.tables.Saldoperiodo.SALDOPERIODO.SALDODEBE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return persistencia.tables.Saldoperiodo.SALDOPERIODO.SALDOHABER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field6() {
		return persistencia.tables.Saldoperiodo.SALDOPERIODO.SALDOFINAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getSaldoperiodoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPeriodocontableid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getSaldodebe();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getSaldohaber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value6() {
		return getSaldofinal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SaldoperiodoRecord value1(java.lang.Integer value) {
		setSaldoperiodoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SaldoperiodoRecord value2(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SaldoperiodoRecord value3(java.lang.Integer value) {
		setPeriodocontableid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SaldoperiodoRecord value4(java.lang.Double value) {
		setSaldodebe(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SaldoperiodoRecord value5(java.lang.Double value) {
		setSaldohaber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SaldoperiodoRecord value6(java.lang.Double value) {
		setSaldofinal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SaldoperiodoRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Double value4, java.lang.Double value5, java.lang.Double value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SaldoperiodoRecord
	 */
	public SaldoperiodoRecord() {
		super(persistencia.tables.Saldoperiodo.SALDOPERIODO);
	}

	/**
	 * Create a detached, initialised SaldoperiodoRecord
	 */
	public SaldoperiodoRecord(java.lang.Integer saldoperiodoid, java.lang.Integer id, java.lang.Integer periodocontableid, java.lang.Double saldodebe, java.lang.Double saldohaber, java.lang.Double saldofinal) {
		super(persistencia.tables.Saldoperiodo.SALDOPERIODO);

		setValue(0, saldoperiodoid);
		setValue(1, id);
		setValue(2, periodocontableid);
		setValue(3, saldodebe);
		setValue(4, saldohaber);
		setValue(5, saldofinal);
	}
}
