/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TipomovimientoRecord extends org.jooq.impl.UpdatableRecordImpl<persistencia.tables.records.TipomovimientoRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -2078152316;

	/**
	 * Setter for <code>modulo_contable_smartwork.tipomovimiento.TIPOMOVIMIENTOID</code>.
	 */
	public void setTipomovimientoid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.tipomovimiento.TIPOMOVIMIENTOID</code>.
	 */
	public java.lang.Integer getTipomovimientoid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.tipomovimiento.NOMBRE</code>.
	 */
	public void setNombre(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.tipomovimiento.NOMBRE</code>.
	 */
	public java.lang.String getNombre() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>modulo_contable_smartwork.tipomovimiento.ESTADO</code>.
	 */
	public void setEstado(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>modulo_contable_smartwork.tipomovimiento.ESTADO</code>.
	 */
	public java.lang.Integer getEstado() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO.TIPOMOVIMIENTOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO.ESTADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getTipomovimientoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getEstado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipomovimientoRecord value1(java.lang.Integer value) {
		setTipomovimientoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipomovimientoRecord value2(java.lang.String value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipomovimientoRecord value3(java.lang.Integer value) {
		setEstado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipomovimientoRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TipomovimientoRecord
	 */
	public TipomovimientoRecord() {
		super(persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO);
	}

	/**
	 * Create a detached, initialised TipomovimientoRecord
	 */
	public TipomovimientoRecord(java.lang.Integer tipomovimientoid, java.lang.String nombre, java.lang.Integer estado) {
		super(persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO);

		setValue(0, tipomovimientoid);
		setValue(1, nombre);
		setValue(2, estado);
	}
}
