/**
 * This class is generated by jOOQ
 */
package persistencia;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>modulo_contable_smartwork</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<persistencia.tables.records.AsientoRecord> KEY_ASIENTO_PRIMARY = UniqueKeys0.KEY_ASIENTO_PRIMARY;
	public static final org.jooq.UniqueKey<persistencia.tables.records.AsientodetalleRecord> KEY_ASIENTODETALLE_PRIMARY = UniqueKeys0.KEY_ASIENTODETALLE_PRIMARY;
	public static final org.jooq.UniqueKey<persistencia.tables.records.PeriodocontableRecord> KEY_PERIODOCONTABLE_PRIMARY = UniqueKeys0.KEY_PERIODOCONTABLE_PRIMARY;
	public static final org.jooq.UniqueKey<persistencia.tables.records.PlandecuentaRecord> KEY_PLANDECUENTA_PRIMARY = UniqueKeys0.KEY_PLANDECUENTA_PRIMARY;
	public static final org.jooq.UniqueKey<persistencia.tables.records.SaldoperiodoRecord> KEY_SALDOPERIODO_PRIMARY = UniqueKeys0.KEY_SALDOPERIODO_PRIMARY;
	public static final org.jooq.UniqueKey<persistencia.tables.records.TipomovimientoRecord> KEY_TIPOMOVIMIENTO_PRIMARY = UniqueKeys0.KEY_TIPOMOVIMIENTO_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<persistencia.tables.records.AsientoRecord, persistencia.tables.records.PeriodocontableRecord> FK_RELATIONSHIP_2 = ForeignKeys0.FK_RELATIONSHIP_2;
	public static final org.jooq.ForeignKey<persistencia.tables.records.AsientoRecord, persistencia.tables.records.TipomovimientoRecord> FK_RELATIONSHIP_1 = ForeignKeys0.FK_RELATIONSHIP_1;
	public static final org.jooq.ForeignKey<persistencia.tables.records.AsientodetalleRecord, persistencia.tables.records.PlandecuentaRecord> FK_RELATIONSHIP_3 = ForeignKeys0.FK_RELATIONSHIP_3;
	public static final org.jooq.ForeignKey<persistencia.tables.records.AsientodetalleRecord, persistencia.tables.records.AsientoRecord> FK_RELATIONSHIP_4 = ForeignKeys0.FK_RELATIONSHIP_4;
	public static final org.jooq.ForeignKey<persistencia.tables.records.PlandecuentaRecord, persistencia.tables.records.PlandecuentaRecord> FK_RELATIONSHIP_7 = ForeignKeys0.FK_RELATIONSHIP_7;
	public static final org.jooq.ForeignKey<persistencia.tables.records.SaldoperiodoRecord, persistencia.tables.records.PlandecuentaRecord> FK_RELATIONSHIP_6 = ForeignKeys0.FK_RELATIONSHIP_6;
	public static final org.jooq.ForeignKey<persistencia.tables.records.SaldoperiodoRecord, persistencia.tables.records.PeriodocontableRecord> FK_RELATIONSHIP_5 = ForeignKeys0.FK_RELATIONSHIP_5;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<persistencia.tables.records.AsientoRecord> KEY_ASIENTO_PRIMARY = createUniqueKey(persistencia.tables.Asiento.ASIENTO, persistencia.tables.Asiento.ASIENTO.ASIENTOID);
		public static final org.jooq.UniqueKey<persistencia.tables.records.AsientodetalleRecord> KEY_ASIENTODETALLE_PRIMARY = createUniqueKey(persistencia.tables.Asientodetalle.ASIENTODETALLE, persistencia.tables.Asientodetalle.ASIENTODETALLE.ASIENTODETALLEID);
		public static final org.jooq.UniqueKey<persistencia.tables.records.PeriodocontableRecord> KEY_PERIODOCONTABLE_PRIMARY = createUniqueKey(persistencia.tables.Periodocontable.PERIODOCONTABLE, persistencia.tables.Periodocontable.PERIODOCONTABLE.PERIODOCONTABLEID);
		public static final org.jooq.UniqueKey<persistencia.tables.records.PlandecuentaRecord> KEY_PLANDECUENTA_PRIMARY = createUniqueKey(persistencia.tables.Plandecuenta.PLANDECUENTA, persistencia.tables.Plandecuenta.PLANDECUENTA.ID);
		public static final org.jooq.UniqueKey<persistencia.tables.records.SaldoperiodoRecord> KEY_SALDOPERIODO_PRIMARY = createUniqueKey(persistencia.tables.Saldoperiodo.SALDOPERIODO, persistencia.tables.Saldoperiodo.SALDOPERIODO.SALDOPERIODOID);
		public static final org.jooq.UniqueKey<persistencia.tables.records.TipomovimientoRecord> KEY_TIPOMOVIMIENTO_PRIMARY = createUniqueKey(persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO, persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO.TIPOMOVIMIENTOID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<persistencia.tables.records.AsientoRecord, persistencia.tables.records.PeriodocontableRecord> FK_RELATIONSHIP_2 = createForeignKey(persistencia.Keys.KEY_PERIODOCONTABLE_PRIMARY, persistencia.tables.Asiento.ASIENTO, persistencia.tables.Asiento.ASIENTO.PERIODOCONTABLEID);
		public static final org.jooq.ForeignKey<persistencia.tables.records.AsientoRecord, persistencia.tables.records.TipomovimientoRecord> FK_RELATIONSHIP_1 = createForeignKey(persistencia.Keys.KEY_TIPOMOVIMIENTO_PRIMARY, persistencia.tables.Asiento.ASIENTO, persistencia.tables.Asiento.ASIENTO.TIPOMOVIMIENTOID);
		public static final org.jooq.ForeignKey<persistencia.tables.records.AsientodetalleRecord, persistencia.tables.records.PlandecuentaRecord> FK_RELATIONSHIP_3 = createForeignKey(persistencia.Keys.KEY_PLANDECUENTA_PRIMARY, persistencia.tables.Asientodetalle.ASIENTODETALLE, persistencia.tables.Asientodetalle.ASIENTODETALLE.ID);
		public static final org.jooq.ForeignKey<persistencia.tables.records.AsientodetalleRecord, persistencia.tables.records.AsientoRecord> FK_RELATIONSHIP_4 = createForeignKey(persistencia.Keys.KEY_ASIENTO_PRIMARY, persistencia.tables.Asientodetalle.ASIENTODETALLE, persistencia.tables.Asientodetalle.ASIENTODETALLE.ASIENTOID);
		public static final org.jooq.ForeignKey<persistencia.tables.records.PlandecuentaRecord, persistencia.tables.records.PlandecuentaRecord> FK_RELATIONSHIP_7 = createForeignKey(persistencia.Keys.KEY_PLANDECUENTA_PRIMARY, persistencia.tables.Plandecuenta.PLANDECUENTA, persistencia.tables.Plandecuenta.PLANDECUENTA.PLA_ID);
		public static final org.jooq.ForeignKey<persistencia.tables.records.SaldoperiodoRecord, persistencia.tables.records.PlandecuentaRecord> FK_RELATIONSHIP_6 = createForeignKey(persistencia.Keys.KEY_PLANDECUENTA_PRIMARY, persistencia.tables.Saldoperiodo.SALDOPERIODO, persistencia.tables.Saldoperiodo.SALDOPERIODO.ID);
		public static final org.jooq.ForeignKey<persistencia.tables.records.SaldoperiodoRecord, persistencia.tables.records.PeriodocontableRecord> FK_RELATIONSHIP_5 = createForeignKey(persistencia.Keys.KEY_PERIODOCONTABLE_PRIMARY, persistencia.tables.Saldoperiodo.SALDOPERIODO, persistencia.tables.Saldoperiodo.SALDOPERIODO.PERIODOCONTABLEID);
	}
}
