/**
 * This class is generated by jOOQ
 */
package persistencia;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuloContableSmartwork extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1741985830;

	/**
	 * The singleton instance of <code>modulo_contable_smartwork</code>
	 */
	public static final ModuloContableSmartwork MODULO_CONTABLE_SMARTWORK = new ModuloContableSmartwork();

	/**
	 * No further instances allowed
	 */
	private ModuloContableSmartwork() {
		super("modulo_contable_smartwork");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			persistencia.tables.Asiento.ASIENTO,
			persistencia.tables.Asientodetalle.ASIENTODETALLE,
			persistencia.tables.Periodocontable.PERIODOCONTABLE,
			persistencia.tables.Plandecuenta.PLANDECUENTA,
			persistencia.tables.Saldoperiodo.SALDOPERIODO,
			persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO);
	}
}
