/**
 * This class is generated by jOOQ
 */
package persistencia;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in modulo_contable_smartwork
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table modulo_contable_smartwork.asiento
	 */
	public static final persistencia.tables.Asiento ASIENTO = persistencia.tables.Asiento.ASIENTO;

	/**
	 * The table modulo_contable_smartwork.asientodetalle
	 */
	public static final persistencia.tables.Asientodetalle ASIENTODETALLE = persistencia.tables.Asientodetalle.ASIENTODETALLE;

	/**
	 * The table modulo_contable_smartwork.periodocontable
	 */
	public static final persistencia.tables.Periodocontable PERIODOCONTABLE = persistencia.tables.Periodocontable.PERIODOCONTABLE;

	/**
	 * The table modulo_contable_smartwork.plandecuenta
	 */
	public static final persistencia.tables.Plandecuenta PLANDECUENTA = persistencia.tables.Plandecuenta.PLANDECUENTA;

	/**
	 * The table modulo_contable_smartwork.saldoperiodo
	 */
	public static final persistencia.tables.Saldoperiodo SALDOPERIODO = persistencia.tables.Saldoperiodo.SALDOPERIODO;

	/**
	 * The table modulo_contable_smartwork.tipomovimiento
	 */
	public static final persistencia.tables.Tipomovimiento TIPOMOVIMIENTO = persistencia.tables.Tipomovimiento.TIPOMOVIMIENTO;
}
