/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asiento implements java.io.Serializable {

	private static final long serialVersionUID = 1238062854;

	private java.lang.Integer  asientoid;
	private java.lang.Integer  periodocontableid;
	private java.lang.Integer  tipomovimientoid;
	private java.sql.Timestamp fechacreacion;
	private java.lang.String   concepto;
	private java.lang.Integer  estado;

	public Asiento() {}

	public Asiento(
		java.lang.Integer  asientoid,
		java.lang.Integer  periodocontableid,
		java.lang.Integer  tipomovimientoid,
		java.sql.Timestamp fechacreacion,
		java.lang.String   concepto,
		java.lang.Integer  estado
	) {
		this.asientoid = asientoid;
		this.periodocontableid = periodocontableid;
		this.tipomovimientoid = tipomovimientoid;
		this.fechacreacion = fechacreacion;
		this.concepto = concepto;
		this.estado = estado;
	}

	public java.lang.Integer getAsientoid() {
		return this.asientoid;
	}

	public void setAsientoid(java.lang.Integer asientoid) {
		this.asientoid = asientoid;
	}

	public java.lang.Integer getPeriodocontableid() {
		return this.periodocontableid;
	}

	public void setPeriodocontableid(java.lang.Integer periodocontableid) {
		this.periodocontableid = periodocontableid;
	}

	public java.lang.Integer getTipomovimientoid() {
		return this.tipomovimientoid;
	}

	public void setTipomovimientoid(java.lang.Integer tipomovimientoid) {
		this.tipomovimientoid = tipomovimientoid;
	}

	public java.sql.Timestamp getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(java.sql.Timestamp fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public java.lang.String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(java.lang.String concepto) {
		this.concepto = concepto;
	}

	public java.lang.Integer getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.Integer estado) {
		this.estado = estado;
	}
}
