/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asientodetalle implements java.io.Serializable {

	private static final long serialVersionUID = 1372614033;

	private java.lang.Integer asientodetalleid;
	private java.lang.Integer id;
	private java.lang.Integer asientoid;
	private java.lang.String  descripcion;
	private java.lang.Double  debe;
	private java.lang.Double  haber;

	public Asientodetalle() {}

	public Asientodetalle(
		java.lang.Integer asientodetalleid,
		java.lang.Integer id,
		java.lang.Integer asientoid,
		java.lang.String  descripcion,
		java.lang.Double  debe,
		java.lang.Double  haber
	) {
		this.asientodetalleid = asientodetalleid;
		this.id = id;
		this.asientoid = asientoid;
		this.descripcion = descripcion;
		this.debe = debe;
		this.haber = haber;
	}

	public java.lang.Integer getAsientodetalleid() {
		return this.asientodetalleid;
	}

	public void setAsientodetalleid(java.lang.Integer asientodetalleid) {
		this.asientodetalleid = asientodetalleid;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAsientoid() {
		return this.asientoid;
	}

	public void setAsientoid(java.lang.Integer asientoid) {
		this.asientoid = asientoid;
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public java.lang.Double getDebe() {
		return this.debe;
	}

	public void setDebe(java.lang.Double debe) {
		this.debe = debe;
	}

	public java.lang.Double getHaber() {
		return this.haber;
	}

	public void setHaber(java.lang.Double haber) {
		this.haber = haber;
	}
}
