/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Periodocontable implements java.io.Serializable {

	private static final long serialVersionUID = -859135767;

	private java.lang.Integer  periodocontableid;
	private java.sql.Timestamp fechainicio;
	private java.sql.Timestamp fechafinal;
	private java.lang.String   nombreperiodo;
	private java.lang.Integer  estado;

	public Periodocontable() {}

	public Periodocontable(
		java.lang.Integer  periodocontableid,
		java.sql.Timestamp fechainicio,
		java.sql.Timestamp fechafinal,
		java.lang.String   nombreperiodo,
		java.lang.Integer  estado
	) {
		this.periodocontableid = periodocontableid;
		this.fechainicio = fechainicio;
		this.fechafinal = fechafinal;
		this.nombreperiodo = nombreperiodo;
		this.estado = estado;
	}

	public java.lang.Integer getPeriodocontableid() {
		return this.periodocontableid;
	}

	public void setPeriodocontableid(java.lang.Integer periodocontableid) {
		this.periodocontableid = periodocontableid;
	}

	public java.sql.Timestamp getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(java.sql.Timestamp fechainicio) {
		this.fechainicio = fechainicio;
	}

	public java.sql.Timestamp getFechafinal() {
		return this.fechafinal;
	}

	public void setFechafinal(java.sql.Timestamp fechafinal) {
		this.fechafinal = fechafinal;
	}

	public java.lang.String getNombreperiodo() {
		return this.nombreperiodo;
	}

	public void setNombreperiodo(java.lang.String nombreperiodo) {
		this.nombreperiodo = nombreperiodo;
	}

	public java.lang.Integer getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.Integer estado) {
		this.estado = estado;
	}
}
