/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Saldoperiodo implements java.io.Serializable {

	private static final long serialVersionUID = 1626263714;

	private java.lang.Integer saldoperiodoid;
	private java.lang.Integer id;
	private java.lang.Integer periodocontableid;
	private java.lang.Double  saldodebe;
	private java.lang.Double  saldohaber;
	private java.lang.Double  saldofinal;

	public Saldoperiodo() {}

	public Saldoperiodo(
		java.lang.Integer saldoperiodoid,
		java.lang.Integer id,
		java.lang.Integer periodocontableid,
		java.lang.Double  saldodebe,
		java.lang.Double  saldohaber,
		java.lang.Double  saldofinal
	) {
		this.saldoperiodoid = saldoperiodoid;
		this.id = id;
		this.periodocontableid = periodocontableid;
		this.saldodebe = saldodebe;
		this.saldohaber = saldohaber;
		this.saldofinal = saldofinal;
	}

	public java.lang.Integer getSaldoperiodoid() {
		return this.saldoperiodoid;
	}

	public void setSaldoperiodoid(java.lang.Integer saldoperiodoid) {
		this.saldoperiodoid = saldoperiodoid;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getPeriodocontableid() {
		return this.periodocontableid;
	}

	public void setPeriodocontableid(java.lang.Integer periodocontableid) {
		this.periodocontableid = periodocontableid;
	}

	public java.lang.Double getSaldodebe() {
		return this.saldodebe;
	}

	public void setSaldodebe(java.lang.Double saldodebe) {
		this.saldodebe = saldodebe;
	}

	public java.lang.Double getSaldohaber() {
		return this.saldohaber;
	}

	public void setSaldohaber(java.lang.Double saldohaber) {
		this.saldohaber = saldohaber;
	}

	public java.lang.Double getSaldofinal() {
		return this.saldofinal;
	}

	public void setSaldofinal(java.lang.Double saldofinal) {
		this.saldofinal = saldofinal;
	}
}
